#ifndef ZMOD_AWG_AXI_CONFIG_H   /* prevent circular inclusions */
#define ZMOD_AWG_AXI_CONFIG_H

#include "xil_io.h"

/* Register offsets */
#define ZMOD_AWG_AXI_CONFIG_CONTROL_REG_OFFSET 0x0
#define ZMOD_AWG_AXI_CONFIG_STATUS_REG_OFFSET 0x4
#define ZMOD_AWG_AXI_CONFIG_EXTCH1LGMULTCOEFF_REG_OFFSET 0x8
#define ZMOD_AWG_AXI_CONFIG_EXTCH1LGADDCOEFF_REG_OFFSET 0xc
#define ZMOD_AWG_AXI_CONFIG_EXTCH1HGMULTCOEFF_REG_OFFSET 0x10
#define ZMOD_AWG_AXI_CONFIG_EXTCH1HGADDCOEFF_REG_OFFSET 0x14
#define ZMOD_AWG_AXI_CONFIG_EXTCH2LGMULTCOEFF_REG_OFFSET 0x18
#define ZMOD_AWG_AXI_CONFIG_EXTCH2LGADDCOEFF_REG_OFFSET 0x1c
#define ZMOD_AWG_AXI_CONFIG_EXTCH2HGMULTCOEFF_REG_OFFSET 0x20
#define ZMOD_AWG_AXI_CONFIG_EXTCH2HGADDCOEFF_REG_OFFSET 0x24
/* CONTROL register bitfields */
#define ZMOD_AWG_AXI_CONFIG_CONTROL_TESTMODE_MASK 0x1

#define ZMOD_AWG_AXI_CONFIG_CONTROL_DAC_ENIN_MASK 0x2

#define ZMOD_AWG_AXI_CONFIG_CONTROL_EXTCH1SCALE_MASK 0x4

#define ZMOD_AWG_AXI_CONFIG_CONTROL_EXTCH2SCALE_MASK 0x8

/* STATUS register bitfields */
#define ZMOD_AWG_AXI_CONFIG_STATUS_INITDONEDAC_MASK 0x1

#define ZMOD_AWG_AXI_CONFIG_STATUS_CONFIGERROR_MASK 0x2

/* EXTCH1LGMULTCOEFF register bitfields */
#define ZMOD_AWG_AXI_CONFIG_EXTCH1LGMULTCOEFF_EXTCH1LGMULTCOEFF_MASK 0x3ffff

/* EXTCH1LGADDCOEFF register bitfields */
#define ZMOD_AWG_AXI_CONFIG_EXTCH1LGADDCOEFF_EXTCH1LGADDCOEFF_MASK 0x3ffff

/* EXTCH1HGMULTCOEFF register bitfields */
#define ZMOD_AWG_AXI_CONFIG_EXTCH1HGMULTCOEFF_EXTCH1HGMULTCOEFF_MASK 0x3ffff

/* EXTCH1HGADDCOEFF register bitfields */
#define ZMOD_AWG_AXI_CONFIG_EXTCH1HGADDCOEFF_EXTCH1HGADDCOEFF_MASK 0x3ffff

/* EXTCH2LGMULTCOEFF register bitfields */
#define ZMOD_AWG_AXI_CONFIG_EXTCH2LGMULTCOEFF_EXTCH2LGMULTCOEFF_MASK 0x3ffff

/* EXTCH2LGADDCOEFF register bitfields */
#define ZMOD_AWG_AXI_CONFIG_EXTCH2LGADDCOEFF_EXTCH2LGADDCOEFF_MASK 0x3ffff

/* EXTCH2HGMULTCOEFF register bitfields */
#define ZMOD_AWG_AXI_CONFIG_EXTCH2HGMULTCOEFF_EXTCH2HGMULTCOEFF_MASK 0x3ffff

/* EXTCH2HGADDCOEFF register bitfields */
#define ZMOD_AWG_AXI_CONFIG_EXTCH2HGADDCOEFF_EXTCH2HGADDCOEFF_MASK 0x3ffff


/* Register access macros */
#define ZmodAwgAxiConfiguration_In32     Xil_In32
#define ZmodAwgAxiConfiguration_Out32	Xil_Out32

#define ZmodAwgAxiConfiguration_ReadReg(BaseAddress, RegOffset)          ZmodAwgAxiConfiguration_In32((BaseAddress) + (RegOffset))
#define ZmodAwgAxiConfiguration_WriteReg(BaseAddress, RegOffset, Data)   ZmodAwgAxiConfiguration_Out32((BaseAddress) + (RegOffset), (Data))

#endif /* end of protection macro */

